
const colorPalettes =
[	
    {hash: 0x3F6E70FF},
    {hash: 0x0105607B},
    {hash: 0x17CBCC83},
    {hash: 0x29F81B2A},
    {hash: 0x3385C5DB},
    {hash: 0x37CD36D4},
    {hash: 0x4101ED87},
    {hash: 0x63838A81},
    {hash: 0x6765BC15},
    {hash: 0x8BA18876},
    {hash: 0x9AC34F34},
    {hash: 0x9E4803A0},
    {hash: 0xA4041CEF},
    {hash: 0xA4CFABD0},
    {hash: 0xAA65D8A3},
    {hash: 0xB562025C},
    {hash: 0xB9E7F722},
    {hash: 0xBBF43EF8},
    {hash: 0xD1476963},
    {hash: 0xD799E1C2},
    {hash: 0xDC6BC93B},
    {hash: 0xDFB1F64C},
    {hash: 0xF509C745},
    {hash: 0xF93DB0C8},
    {hash: 0xFB71527B}
];


const eMetapedBodyApparatusGender = 
{
    Invalid: -1,
    Female: 0,
    Male: 1,
}

const eMetapedBodyApparatusType =
{
    Invalid           : -1,
    Hair              : 0,
    Heads             : 1,
    BodiesLower       : 2,
    BodiesUpper       : 3,
    Teeth             : 4,
    Eyes              : 5,
    Hats              : 6,
    ShirtsFull        : 7,
    Vests             : 8,
    Coats             : 9,
    CoatsClosed       : 10,
    Pants             : 11,
    Boots             : 12,
    BootAccessories   : 13,
    Cloaks            : 14,
    Chaps             : 15,
    Badges            : 16,
    Masks             : 17,
    Spats             : 18,
    Neckwear          : 19,
    Accessories       : 20,
    JewelryRingsRight : 21,
    JewelryRingsLeft  : 22,
    JewelryBracelets  : 23,
    Gauntlets         : 24,
    Neckties          : 25,
    Loadouts          : 26,
    Suspenders        : 27,
    Satchels          : 28,
    Gunbelts          : 29,
    Belts             : 30,
    BeltBuckles       : 31,
    HolstersLeft      : 32,
    Ponchos           : 33,
    Armor             : 34,
    Eyewear           : 35,
    Gloves            : 36,
    LegsAcessories    : 37,
    Skirts : 38,
    BeardsComplete : 39,
    HairAccessories : 40,
}

const eMetapedExpressionTypeRDR3 = {
    FaceWidth : 0,
    BrowHeight : 1,
    BrowWidth : 2,
    BrowDepth : 3,
    EarSize : 4,
    EarRotation : 5,
    EarLength : 6,
    EarLobe : 7,
    CheeksHeight : 8,
    CheeksWidth : 9,
    CheeksDepth : 10,
    JawHeight : 11,
    JawWidth : 12,
    JawDepth : 13,
    ChinTilt : 14,
    ChinWidth : 15,
    ChinDepth : 16,
    EyeHeight : 17,
    EyeWidth : 18,
    EyeDepth : 19,
    EyeAngle : 20,
    EyeHPos : 21,
    EyeVPos : 22,
    NoseWidth : 23,
    NoseLength : 24,
    NoseHeight : 25,
    NoseTilt : 26,
    NoseBreak : 27,
    NostrilWidth : 28,
    MouthWidth : 29,
    MouthDepth : 30,
    MouthHPos : 31,
    MouthVPos : 32,
    UpperLipThickness : 33,
    UpperLipWidth : 34,
    UpperLipDepth : 35,
    LowerLipThickness : 36,
    LowerLipWidth : 37,
    LowerLipDepth : 38,
}

const eMetapedBodyApparatusTypeToStr = 
{
    [-1]: "Invalid",
    [0] : "Hair",
    [1] : "Heads",
    [2] : "BodiesLower",
    [3] : "BodiesUpper",
    [4] : "Teeth",
    [5] : "Eyes",
    [6] : "Hats",
    [7] : "ShirtsFull",
    [8] : "Vests",
    [9] : "Coats",
    [10] : "CoatsClosed",
    [11] : "Pants",
    [12] : "Boots",
    [13] : "BootAccessories",
    [14] : "Cloaks",
    [15] : "Chaps",
    [16] : "Badges",
    [17] : "Masks",
    [18] : "Spats",
    [19] : "Neckwear",
    [20] : "Accessories",
    [21] : "JewelryRingsRight",
    [22] : "JewelryRingsLeft",
    [23] : "JewelryBracelets",
    [24] : "Gauntlets",
    [25] : "Neckties",
    [26] : "Loadouts",
    [27] : "Suspenders",
    [28] : "Satchels",
    [29] : "Gunbelts",
    [30] : "Belts",
    [31] : "BeltBuckles",
    [32] : "HolstersLeft",
    [33] : "Ponchos",
    [34] : "Armor",
    [35] : "Eyewear",
    [36] : "Gloves",
    [37] : "LegsAcessories",
    [38] : "Skirts",
    [39] : "BeardsComplete",
    [40] : "HairAccessories",
}

const eOverlayLayer = {
    NONE : 0,
    MPC_OVERLAY_LAYER_FACIAL_HAIR : 1,
    MPC_OVERLAY_LAYER_FOUNDATION : 2,
    MPC_OVERLAY_LAYER_HEAD_HAIR : 3,
    MPC_OVERLAY_LAYER_COMPLEXION : 4,
    MPC_OVERLAY_LAYER_ROOT : 5,
    MPC_OVERLAY_LAYER_EYESHADOW : 6,
    MPC_OVERLAY_LAYER_LIPSTICK : 7,
    MPC_OVERLAY_LAYER_FACE_PAINT : 8,
    MPC_OVERLAY_LAYER_COMPLEXION_2 : 9,
    MPC_OVERLAY_LAYER_EYELINER : 10,
    MPC_OVERLAY_LAYER_INVALID : 11,
    MPC_OVERLAY_LAYER_SKIN_MOTTLING : 12,
    MPC_OVERLAY_LAYER_FRECKLES : 13,
    MPC_OVERLAY_LAYER_AGEING : 14,
    MPC_OVERLAY_LAYER_BLUSHER : 15,
    MPC_OVERLAY_LAYER_EYEBROWS : 16,
    MPC_OVERLAY_LAYER_GRIME : 17,
    MPC_OVERLAY_LAYER_SPOTS : 18,
    MPC_OVERLAY_LAYER_MOLES : 19,
    MPC_OVERLAY_LAYER_SCAR : 20,
}

const eOverlayToStr = {
    [0] : "NONE",
    [1] : "MPC_OVERLAY_LAYER_FACIAL_HAIR",
    [2] : "MPC_OVERLAY_LAYER_FOUNDATION",
    [3] : "MPC_OVERLAY_LAYER_HEAD_HAIR",
    [4] : "MPC_OVERLAY_LAYER_COMPLEXION",
    [5] : "MPC_OVERLAY_LAYER_ROOT",
    [6] : "MPC_OVERLAY_LAYER_EYESHADOW",
    [7] : "MPC_OVERLAY_LAYER_LIPSTICK",
    [8] : "MPC_OVERLAY_LAYER_FACE_PAINT",
    [9] : "MPC_OVERLAY_LAYER_COMPLEXION_2",
    [10] : "MPC_OVERLAY_LAYER_EYELINER",
    [11] : "MPC_OVERLAY_LAYER_INVALID",
    [12] : "MPC_OVERLAY_LAYER_SKIN_MOTTLING",
    [13] : "MPC_OVERLAY_LAYER_FRECKLES",
    [14] : "MPC_OVERLAY_LAYER_AGEING",
    [15] : "MPC_OVERLAY_LAYER_BLUSHER",
    [16] : "MPC_OVERLAY_LAYER_EYEBROWS",
    [17] : "MPC_OVERLAY_LAYER_GRIME",
    [18] : "MPC_OVERLAY_LAYER_SPOTS",
    [19] : "MPC_OVERLAY_LAYER_MOLES",
    [20] : "MPC_OVERLAY_LAYER_SCAR",
}



const MetapedExpressionToHash =
{
    [eMetapedExpressionTypeRDR3.FaceWidth]: 0x84D6,
    [eMetapedExpressionTypeRDR3.BrowHeight]: 0x3303,//GetHashKey('PEDEXPRESS_BROW_HEIGHT'),
    [eMetapedExpressionTypeRDR3.BrowWidth]: 0x2FF9,//GetHashKey('PEDEXPRESS_BROW_WIDTH'),
    [eMetapedExpressionTypeRDR3.BrowDepth]: 0x4AD1,//GetHashKey('PEDEXPRESS_BROW_DEPTH'),

    [eMetapedExpressionTypeRDR3.EarSize]: 0x2844,//GetHashKey('PEDEXPRESS_EAR_SIZE'),
    [eMetapedExpressionTypeRDR3.EarRotation]: 0xB6CE,//GetHashKey('PEDEXPRESS_EAR_ROTATION'),
    [eMetapedExpressionTypeRDR3.EarLength]: 0xC04F,//GetHashKey('PEDEXPRESS_EAR_LENGTH'),
    [eMetapedExpressionTypeRDR3.EarLobe]: 0xED30,//GetHashKey('PEDEXPRESS_EAR_LOBE'),

    [eMetapedExpressionTypeRDR3.CheeksHeight]: 0x6A0B,//GetHashKey('PEDEXPRESS_CHEEKS_HEIGHT'),
    [eMetapedExpressionTypeRDR3.CheeksWidth]: 0xABCF,//GetHashKey('PEDEXPRESS_CHEEKS_WIDTH'),
    [eMetapedExpressionTypeRDR3.CheeksDepth]: 0x358D,//GetHashKey('PEDEXPRESS_CHEEKS_DEPTH'),

    [eMetapedExpressionTypeRDR3.JawHeight]: 0x8D0A,//GetHashKey('PEDEXPRESS_JAW_HEIGHT'),
    [eMetapedExpressionTypeRDR3.JawWidth]: 0xEBAE,//GetHashKey('PEDEXPRESS_JAW_WIDTH'),
    [eMetapedExpressionTypeRDR3.JawDepth]: 0x1DF6,//GetHashKey('PEDEXPRESS_JAW_DEPTH'),

    [eMetapedExpressionTypeRDR3.ChinTilt]: 0x3C0F,//GetHashKey('PEDEXPRESS_CHIN_TILT'),
    [eMetapedExpressionTypeRDR3.ChinWidth]: 0xC3B2,//GetHashKey('PEDEXPRESS_CHIN_WIDTH'),
    [eMetapedExpressionTypeRDR3.ChinDepth]: 0xE323,//GetHashKey('PEDEXPRESS_CHIN_DEPTH'),

    [eMetapedExpressionTypeRDR3.EyeHeight]: 0xDDFB,//GetHashKey('PEDEXPRESS_EYE_HEIGHT'),
    [eMetapedExpressionTypeRDR3.EyeWidth]: 0xA54E,//GetHashKey('PEDEXPRESS_EYE_WIDTH'),
    
    [eMetapedExpressionTypeRDR3.EyeDepth]: 0xEE44,//GetHashKey('PEDEXPRESS_EYE_DEPTH'),
    [eMetapedExpressionTypeRDR3.EyeAngle]: 0xD266,//GetHashKey('PEDEXPRESS_EYE_ANGLE'),

    [eMetapedExpressionTypeRDR3.EyeHPos]: 0x1B6B,//GetHashKey('PEDEXPRESS_EYE_H_POS'),
    [eMetapedExpressionTypeRDR3.EyeVPos]: 0x8B2B,//GetHashKey('PEDEXPRESS_EYE_V_POS'),

    [eMetapedExpressionTypeRDR3.NoseWidth]: 0x6E7F,//GetHashKey('PEDEXPRESS_NOSE_WIDTH'),
    [eMetapedExpressionTypeRDR3.NoseLength]: 0x3471,//GetHashKey('PEDEXPRESS_NOSE_LENGTH'),
    [eMetapedExpressionTypeRDR3.NoseHeight]: 0x03F5,//GetHashKey('PEDEXPRESS_NOSE_HEIGHT'),
    [eMetapedExpressionTypeRDR3.NoseTilt]: 0xF156,//GetHashKey('PEDEXPRESS_NOSE_TILT'),
    [eMetapedExpressionTypeRDR3.NoseBreak]: 0x34B1,//GetHashKey('PEDEXPRESS_NOSE_BREAK'),
    
    [eMetapedExpressionTypeRDR3.NostrilWidth]: 0x561E,//GetHashKey('PEDEXPRESS_NOSTRIL_WIDTH'),
    
    [eMetapedExpressionTypeRDR3.MouthWidth]: 0xF065,//GetHashKey('PEDEXPRESS_MOUTH_WIDTH'),
    [eMetapedExpressionTypeRDR3.MouthDepth]: 0xAA69,//GetHashKey('PEDEXPRESS_MOUTH_DEPTH'),
    [eMetapedExpressionTypeRDR3.MouthHPos]: 0x7AC3,//GetHashKey('PEDEXPRESS_MOUTH_H_POS'),
    [eMetapedExpressionTypeRDR3.MouthVPos]: 0x410D,//GetHashKey('PEDEXPRESS_MOUTH_V_POS'),
    
    [eMetapedExpressionTypeRDR3.UpperLipThickness]: 0x1A00,//GetHashKey('PEDEXPRESS_UPPER_LIP_THICKNESS'),
    [eMetapedExpressionTypeRDR3.UpperLipWidth]: 0x91C1,//GetHashKey('PEDEXPRESS_UPPER_LIP_WIDTH'),
    [eMetapedExpressionTypeRDR3.UpperLipDepth]: 0xC375,//GetHashKey('PEDEXPRESS_UPPER_LIPDEPTH'),
    
    [eMetapedExpressionTypeRDR3.LowerLipThickness]: 0xBB4D,//GetHashKey('PEDEXPRESS_LOWER_LIP_THICKNESS'),
    [eMetapedExpressionTypeRDR3.LowerLipWidth]: 0xB0B0,//GetHashKey('PEDEXPRESS_LOWER_LIP_WIDTH'),
    [eMetapedExpressionTypeRDR3.LowerLipDepth]: 0x5D16//GetHashKey('PEDEXPRESS_LOWER_LIP_DEPTH'),
}
